### ISSUE TITLE
ROS Flight Control

### ISSUE THREAD

**Issue by kuederleR** [kuederleR/aeroprint#2]
Dig into figure 8 ROS script to see how to control the flight.

**Comment by marshallt6** [comment]
Flight is controlled by position velocity acceleration and yaw vectors. position = position' = position '' . To make the drone face yaw will be with respect to acceleration instead of velocity from the original algorithm used. Will test in simulation software.

**Comment by kuederleR** [comment]
Basic flight control achieved
